# Setup
title: Calendario Interactivo
tagline: El calendario que andabas buscando

# About/contact
author:
  name:       Gabriel Castro, Carlos Sánchez y Manuel Orantes

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-cayman
description: El calendario que andabas buscando